Repository kgu-capstone/study-with-me-be, pull requests merged in 2023-03, with the labels that each got.

#2 [docs] PR 및 Issue 템플릿을 등록한다
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: setting

#4 [chore] 기본 프로젝트 설정을 진행한다
  build.gradle
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: chore, setting

#6 [feat] 전역 예외를 한곳에서 처리하기 위해서 ExceptionHandler를 커스텀한다
  src/main/java/com/kgu/studywithme/global/dto/SimpleResponseWrapper.java
  src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
  src/main/java/com/kgu/studywithme/global/exception/ErrorCode.java
  src/main/java/com/kgu/studywithme/global/exception/ErrorResponse.java
  src/main/java/com/kgu/studywithme/global/exception/GlobalErrorCode.java
  src/main/java/com/kgu/studywithme/global/exception/StudyWithMeException.java
Labels: feature

#9 [feat] Member Entity를 설계한다
  build.gradle
  src/main/java/com/kgu/studywithme/member/domain/Email.java
  src/main/java/com/kgu/studywithme/member/domain/Gender.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
  src/main/java/com/kgu/studywithme/member/domain/Password.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/test/java/com/kgu/studywithme/StudywithmeApplicationTests.java
  src/test/java/com/kgu/studywithme/common/utils/PasswordEncoderUtils.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/domain/EmailTest.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/domain/PasswordTest.java
Labels: feature

#10 [feat] Token 기반 인증을 위한 기초 설계를 진행한다
  src/main/java/com/kgu/studywithme/auth/exception/AuthErrorCode.java
  src/main/java/com/kgu/studywithme/auth/utils/AuthorizationExtractor.java
  src/main/java/com/kgu/studywithme/auth/utils/JwtTokenProvider.java
  src/main/java/com/kgu/studywithme/global/annotation/ExtractPayload.java
  src/main/java/com/kgu/studywithme/global/annotation/ExtractPayloadArgumentResolver.java
  src/main/java/com/kgu/studywithme/global/annotation/ExtractToken.java
  src/main/java/com/kgu/studywithme/global/annotation/ExtractTokenArgumentResolver.java
  src/main/java/com/kgu/studywithme/global/config/ArgumentResolverConfiguration.java
  src/main/java/com/kgu/studywithme/global/config/JpaAuditingConfiguration.java
  src/main/java/com/kgu/studywithme/global/config/QueryDslConfiguration.java
  src/test/java/com/kgu/studywithme/auth/utils/JwtTokenProviderTest.java
Labels: feature

#12 [feat] 토큰 관리에 대한 로직을 구현한다
  src/docs/asciidoc/token-reissue.adoc
  src/main/java/com/kgu/studywithme/auth/controller/TokenReissueApiController.java
  src/main/java/com/kgu/studywithme/auth/domain/Token.java
  src/main/java/com/kgu/studywithme/auth/domain/TokenRepository.java
  src/main/java/com/kgu/studywithme/auth/service/TokenManager.java
  src/main/java/com/kgu/studywithme/auth/service/TokenReissueService.java
  src/main/java/com/kgu/studywithme/auth/service/dto/response/TokenResponse.java
  src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/domain/TokenRepositoryTest.java
  src/test/java/com/kgu/studywithme/auth/service/TokenManagerTest.java
  src/test/java/com/kgu/studywithme/auth/service/TokenReissueServiceTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/DatabaseCleaner.java
  src/test/java/com/kgu/studywithme/common/RepositoryTest.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/common/utils/TokenUtils.java
Labels: feature, test

#17 [feat] Member Entity 수정과 스터디 카테고리에 대한 설계를 진행한다
  src/main/java/com/kgu/studywithme/StudyWithMeApplication.java
  src/main/java/com/kgu/studywithme/category/domain/Category.java
  src/main/java/com/kgu/studywithme/category/exception/CategoryErrorCode.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/Nickname.java
  src/main/java/com/kgu/studywithme/member/domain/Region.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/kgu/studywithme/category/domain/CategoryTest.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/domain/NicknameTest.java
Labels: feature, test

#19 [feat] 회원가입 로직을 구현한다
  src/docs/asciidoc/member-signup.adoc
  src/main/java/com/kgu/studywithme/auth/service/dto/response/TokenResponse.java
  src/main/java/com/kgu/studywithme/global/config/AdditionalWebConfiguration.java
  src/main/java/com/kgu/studywithme/global/utils/PasswordEncoderUtils.java
  src/main/java/com/kgu/studywithme/member/controller/MemberApiController.java
  src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
  src/main/java/com/kgu/studywithme/member/domain/Gender.java
  src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/java/com/kgu/studywithme/member/exception/MemberRequestValidationMessage.java
  src/main/java/com/kgu/studywithme/member/service/MemberSignUpService.java
  src/main/java/com/kgu/studywithme/member/service/MemberValidator.java
  src/test/java/com/kgu/studywithme/category/domain/CategoryTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
  src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberValidatorTest.java
Labels: feature, test

#22 [feat] 서비스 자체 로그인 & 로그아웃 로직을 구현한다
  src/docs/asciidoc/auth.adoc
  src/main/java/com/kgu/studywithme/auth/controller/AuthApiController.java
  src/main/java/com/kgu/studywithme/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/kgu/studywithme/auth/exception/AuthRequestValidationMessage.java
  src/main/java/com/kgu/studywithme/auth/service/AuthService.java
  src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/java/com/kgu/studywithme/member/service/MemberFindService.java
  src/test/java/com/kgu/studywithme/auth/controller/AuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/utils/LoginRequestUtils.java
  src/test/java/com/kgu/studywithme/auth/service/AuthServiceTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberFindServiceTest.java
Labels: feature

#24 [feat] 소셜 로그인 기능을 구현한다
  src/docs/asciidoc/oauth.adoc
  src/main/java/com/kgu/studywithme/auth/controller/OAuthApiController.java
  src/main/java/com/kgu/studywithme/auth/controller/dto/request/OAuthLoginRequest.java
  src/main/java/com/kgu/studywithme/auth/exception/AuthErrorCode.java
  src/main/java/com/kgu/studywithme/auth/exception/AuthRequestValidationMessage.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/GoogleOAuthConnector.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/GoogleOAuthUri.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/OAuthConnector.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/OAuthProperties.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/OAuthUri.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/GoogleTokenResponse.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/GoogleUserResponse.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/OAuthTokenResponse.java
  src/main/java/com/kgu/studywithme/auth/infra/oauth/dto/response/OAuthUserResponse.java
  src/main/java/com/kgu/studywithme/auth/service/OAuthService.java
  src/main/java/com/kgu/studywithme/global/config/RestTemplateConfiguration.java
  src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
  src/main/java/com/kgu/studywithme/global/exception/StudyWithMeOAuthException.java
  src/main/resources/application-test.yml
  src/test/java/com/kgu/studywithme/auth/controller/AuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/utils/OAuthLoginRequestUtils.java
  src/test/java/com/kgu/studywithme/auth/infra/oauth/OAuthUriTest.java
  src/test/java/com/kgu/studywithme/auth/service/OAuthServiceTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/InfraTest.java
  src/test/java/com/kgu/studywithme/common/config/MockMvcConfiguration.java
  src/test/java/com/kgu/studywithme/common/utils/TokenUtils.java
Labels: feature

#25 [refactor] REST Docs 문서를 커스터마이징한다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/oauth.adoc
  src/test/java/com/kgu/studywithme/auth/controller/AuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/config/MockMvcConfiguration.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: refactor, test

#29 [chore] CI(Continuous Integration) 환경을 구축한다
  .github/workflows/backend-ci.yml
  .gitignore
Labels: bug, setting

#31 [feat] 전체 카테고리 조회 API를 구현한다
  .github/workflows/backend-ci.yml
  src/docs/asciidoc/category.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/kgu/studywithme/category/controller/CategoryApiController.java
  src/main/java/com/kgu/studywithme/category/service/CategoryService.java
  src/main/java/com/kgu/studywithme/category/service/dto/response/CategoryResponse.java
  src/test/java/com/kgu/studywithme/category/controller/CategoryApiControllerTest.java
  src/test/java/com/kgu/studywithme/category/service/CategoryServiceTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
Labels: feature

#33 [chore] CI 테스트 결과에 대한 action을 수정한다
  .github/workflows/backend-ci.yml
Labels: chore

#35 [chore] Git Submodule 및 Github Actions CI 제거
  .gitignore
Labels: chore

#54 [refactor] 자체 로그인 기능 제거에 따른 사용자 도메인 변경사항을 반영한다
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/oauth.adoc
  src/main/java/com/kgu/studywithme/auth/controller/AuthApiController.java
  src/main/java/com/kgu/studywithme/auth/controller/OAuthApiController.java
  src/main/java/com/kgu/studywithme/auth/controller/dto/request/LoginRequest.java
  src/main/java/com/kgu/studywithme/auth/service/AuthService.java
  src/main/java/com/kgu/studywithme/auth/service/OAuthService.java
  src/main/java/com/kgu/studywithme/global/utils/PasswordEncoderUtils.java
  src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/Password.java
  src/main/java/com/kgu/studywithme/member/exception/MemberRequestValidationMessage.java
  src/test/java/com/kgu/studywithme/auth/controller/AuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/utils/LoginRequestUtils.java
  src/test/java/com/kgu/studywithme/auth/service/AuthServiceTest.java
  src/test/java/com/kgu/studywithme/auth/service/OAuthServiceTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/utils/PasswordEncoderUtils.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/domain/PasswordTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
Labels: refactor

#55 [refactor] 로그인 성공 시 응답 스펙을 수정한다
  src/main/java/com/kgu/studywithme/auth/controller/OAuthApiController.java
  src/main/java/com/kgu/studywithme/auth/service/OAuthService.java
  src/main/java/com/kgu/studywithme/auth/service/dto/response/LoginResponse.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/service/OAuthServiceTest.java
Labels: refactor

#56 [refactor] RestTemplate 빈 설정을 수정한다
  src/main/java/com/kgu/studywithme/global/config/RestTemplateConfiguration.java
Labels: refactor

#59 [refactor] MockMvc 테스트 결과에 대한 검증에 사용되는 andExpect를 andExpectAll로 수정한다
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/domain/TokenRepositoryTest.java
  src/test/java/com/kgu/studywithme/auth/service/OAuthServiceTest.java
  src/test/java/com/kgu/studywithme/auth/service/TokenManagerTest.java
  src/test/java/com/kgu/studywithme/auth/service/TokenReissueServiceTest.java
  src/test/java/com/kgu/studywithme/category/controller/CategoryApiControllerTest.java
  src/test/java/com/kgu/studywithme/category/service/CategoryServiceTest.java
  src/test/java/com/kgu/studywithme/common/InfraTest.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
  src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberFindServiceTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberValidatorTest.java
Labels: refactor, test

#60 [refactor] JWT Token에 대한 유효성 검사를 Spring Interceptor에서 진행하도록 수정한다
  src/main/java/com/kgu/studywithme/global/annotation/ExtractPayloadArgumentResolver.java
  src/main/java/com/kgu/studywithme/global/annotation/ExtractTokenArgumentResolver.java
  src/main/java/com/kgu/studywithme/global/config/AdditionalWebConfiguration.java
  src/main/java/com/kgu/studywithme/global/interceptor/TokenValidityInterceptor.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/TokenReissueApiControllerTest.java
Labels: refactor

#61 [feat] CORS 설정을 추가한다
  src/main/java/com/kgu/studywithme/global/config/AdditionalWebConfiguration.java
  src/main/java/com/kgu/studywithme/global/interceptor/TokenValidityInterceptor.java
Labels: feature

#63 [feat] 생성/수정 시간과 관련된 필드를 포함한 BaseEntity를 구현한다
  src/main/java/com/kgu/studywithme/global/BaseEntity.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
Labels: feature

#66 [refactor] 사용자 도메인에 React Avatar Url에 대한 필드를 추가한다
  src/main/java/com/kgu/studywithme/auth/service/OAuthService.java
  src/main/java/com/kgu/studywithme/auth/service/dto/response/LoginResponse.java
  src/main/java/com/kgu/studywithme/auth/service/dto/response/MemberInfo.java
  src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
Labels: refactor

#67 [feat] 특정 스터디에 대한 참여 신청/승인/거부/취소 API를 구현한다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/study-participation.adoc
  src/main/java/com/kgu/studywithme/member/service/MemberFindService.java
  src/main/java/com/kgu/studywithme/study/controller/StudyParticipationApiController.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/service/ParticipationService.java
  src/main/java/com/kgu/studywithme/study/service/StudyFindService.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberFindServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyParticipationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
Labels: feature

#70 [fix] 구글 프로필 이미지가 업데이트 된 경우 서비스상에서 업데이트 되지 않는 이슈를 수정한다
  src/main/java/com/kgu/studywithme/auth/service/dto/response/MemberInfo.java
  src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/RealProfile.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
Labels: bug

#73 [refactor] 구글 프로필 이미지를 사용하지 않음에 따라 로직을 수정한다
  src/main/java/com/kgu/studywithme/auth/service/OAuthService.java
  src/main/java/com/kgu/studywithme/auth/service/dto/response/MemberInfo.java
  src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/RealProfile.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
Labels: refactor

#74 [refactor] 오프라인 스터디 진행 지역에 대한 필드를 추가한다
  src/main/java/com/kgu/studywithme/category/exception/CategoryErrorCode.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/StudyArea.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/resources/application-dev.yml
  src/test/java/com/kgu/studywithme/fixture/StudyFixture.java
  src/test/java/com/kgu/studywithme/study/domain/StudyAreaTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentsTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/submit/SubmitTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceTest.java
  src/test/java/com/kgu/studywithme/study/domain/notice/NoticeTest.java
  src/test/java/com/kgu/studywithme/study/domain/notice/comment/CommentTest.java
  src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantTest.java
  src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantsTest.java
  src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
Labels: refactor

#80 [feat] 스터디 종료 시 작성할 수 있는 Review를 설계한다
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/participant/Participants.java
  src/main/java/com/kgu/studywithme/study/domain/review/Review.java
  src/main/java/com/kgu/studywithme/study/domain/review/ReviewRepository.java
  src/main/java/com/kgu/studywithme/study/domain/review/Reviews.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentsTest.java
  src/test/java/com/kgu/studywithme/study/domain/review/ReviewTest.java
  src/test/java/com/kgu/studywithme/study/domain/review/ReviewsTest.java
Labels: feature

#81 [refactor] Authorization Code를 React에서 보낼때 body로 보내지 않고 queryString으로 보내도록 수정한다
  src/docs/asciidoc/oauth.adoc
  src/main/java/com/kgu/studywithme/auth/controller/OAuthApiController.java
  src/main/java/com/kgu/studywithme/auth/controller/dto/request/OAuthLoginRequest.java
  src/main/java/com/kgu/studywithme/auth/exception/AuthRequestValidationMessage.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/auth/controller/utils/OAuthLoginRequestUtils.java
Labels: refactor

#82 [feat] 스터디 생성 API를 구현한다
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/study-register.adoc
  src/main/java/com/kgu/studywithme/study/controller/StudyApiController.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyRegisterRequest.java
  src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/service/StudyRegisterService.java
  src/main/java/com/kgu/studywithme/study/service/StudyValidator.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/utils/StudyRegisterRequestUtils.java
  src/test/java/com/kgu/studywithme/study/service/StudyRegisterServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyValidatorTest.java
Labels: feature

#85 [refactor] @ElementCollection을 Entity 관계로 수정한다
  src/docs/asciidoc/study-register.adoc
  src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/interest/Interest.java
  src/main/java/com/kgu/studywithme/member/domain/interest/InterestRepository.java
  src/main/java/com/kgu/studywithme/study/controller/StudyApiController.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/hashtag/Hashtag.java
  src/main/java/com/kgu/studywithme/study/domain/hashtag/HashtagRepository.java
  src/main/java/com/kgu/studywithme/study/service/StudyRegisterService.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/utils/StudyRegisterRequestUtils.java
  src/test/java/com/kgu/studywithme/study/domain/StudyRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyRegisterServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyValidatorTest.java
Labels: refactor

#86 [feat] 스터디 찜 등록/취소 API를 구현한다
  src/docs/asciidoc/favorite-like.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/kgu/studywithme/favorite/controller/FavoriteApiController.java
  src/main/java/com/kgu/studywithme/favorite/domain/FavoriteRepository.java
  src/main/java/com/kgu/studywithme/favorite/exception/FavoriteErrorCode.java
  src/main/java/com/kgu/studywithme/favorite/service/FavoriteManageService.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/favorite/controller/FavoriteApiControllerTest.java
  src/test/java/com/kgu/studywithme/favorite/service/FavoriteManageServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
Labels: feature

#87 [feat] Github Actions Workflows CI 작업을 추가한다
  .github/workflows/backend-ci.yml
  src/docs/asciidoc/favorite-like.adoc
  src/main/java/com/kgu/studywithme/favorite/controller/FavoriteApiController.java
  src/main/java/com/kgu/studywithme/favorite/domain/FavoriteRepository.java
  src/main/java/com/kgu/studywithme/favorite/service/FavoriteManageService.java
  src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/resources/application-test.yml
  src/test/java/com/kgu/studywithme/favorite/controller/FavoriteApiControllerTest.java
  src/test/java/com/kgu/studywithme/favorite/domain/FavoriteRepositoryTest.java
  src/test/java/com/kgu/studywithme/favorite/service/FavoriteManageServiceTest.java
Labels: feature

#90 [fix] Github Actions CI가 동작하지 않는 이슈를 해결한다
  .github/workflows/ci.yml
Labels: bug

#92 [feat] Github Actions Workflows CI 작업을 추가한다 (Retry)
  .github/workflows/backend-ci.yml
Labels: feature
