Repository kgu-capstone/study-with-me-be, pull requests merged in 2023-04, with the labels that each got.

#93 [feat] 각 카테고리에 해당하는 스터디 리스트 조회 API를 구현한다
  src/docs/asciidoc/study-basic-search.adoc
  src/main/java/com/kgu/studywithme/study/controller/StudySearchApiController.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyCategorySearchRequest.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyRecommendSearchRequest.java
  src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicHashtag.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicStudy.java
  src/main/java/com/kgu/studywithme/study/service/StudySearchService.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/DefaultStudyResponse.java
  src/main/java/com/kgu/studywithme/study/utils/PagingConstants.java
  src/main/java/com/kgu/studywithme/study/utils/StudyCategoryCondition.java
  src/main/java/com/kgu/studywithme/study/utils/StudyRecommendCondition.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/fixture/StudyFixture.java
  src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
Labels: feature

#103 [feat] 스터디 상세 페이지 정보 조회 API를 구현한다
  src/docs/asciidoc/study-information.adoc
  src/main/java/com/kgu/studywithme/member/utils/MemberAgeCalculator.java
  src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
  src/main/java/com/kgu/studywithme/study/domain/review/Reviews.java
  src/main/java/com/kgu/studywithme/study/service/StudyFindService.java
  src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/ReviewAssembler.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyHost.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyReview.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyReviewer.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/review/ReviewsTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: feature

#104 [refactor & fix] 메인페이지 스터디 조회 타입에 온/오프 통합을 추가한다
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyCategorySearchRequest.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyRecommendSearchRequest.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/participant/Participants.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/utils/StudyCategoryCondition.java
  src/main/java/com/kgu/studywithme/study/utils/StudyRecommendCondition.java
  src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantsTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
Labels: bug, refactor

#105 [refactor] 사용자 프로필 이미지 생성 방식 수정에 의해서 profileUrl을 제거한다
  src/main/java/com/kgu/studywithme/auth/service/dto/response/MemberInfo.java
  src/main/java/com/kgu/studywithme/member/controller/dto/request/SignUpRequest.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyHost.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyReviewer.java
  src/test/java/com/kgu/studywithme/auth/controller/OAuthApiControllerTest.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberSignUpServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
Labels: refactor

#107 [feat] 스터디 공지사항에 대한 API를 구현한다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/study-notice.adoc
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/java/com/kgu/studywithme/study/controller/StudyNoticeApiController.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/NoticeRequest.java
  src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
  src/main/java/com/kgu/studywithme/study/domain/notice/Notice.java
  src/main/java/com/kgu/studywithme/study/domain/notice/NoticeRepository.java
  src/main/java/com/kgu/studywithme/study/domain/notice/comment/CommentRepository.java
  src/main/java/com/kgu/studywithme/study/exception/NoticeErrorCode.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/service/NoticeService.java
  src/main/java/com/kgu/studywithme/study/service/StudyValidator.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyNoticeApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/utils/NoticeRequestUtils.java
  src/test/java/com/kgu/studywithme/study/domain/StudyRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/notice/NoticeRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/notice/comment/CommentRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/NoticeServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyValidatorTest.java
Labels: feature

#106 [feat] 마이페이지 사용자 관련 API를 구현한다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member-information.adoc
  src/main/java/com/kgu/studywithme/global/annotation/ValidMember.java
  src/main/java/com/kgu/studywithme/global/annotation/ValidMemberAspect.java
  src/main/java/com/kgu/studywithme/global/config/AopConfiguration.java
  src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
  src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
  src/main/java/com/kgu/studywithme/member/service/MemberFindService.java
  src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
  src/main/java/com/kgu/studywithme/member/service/dto/response/MemberInformation.java
  src/main/java/com/kgu/studywithme/member/service/dto/response/RelatedStudy.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/SimpleStudy.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/config/TestAopConfiguration.java
  src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/PeriodTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
Labels: feature

#110 [feat] 스터디 졸업자의 리뷰 작성 API를 구현한다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/study-register.adoc
  src/docs/asciidoc/study-review.adoc
  src/main/java/com/kgu/studywithme/study/controller/StudyReviewApiController.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/ReviewRequest.java
  src/main/java/com/kgu/studywithme/study/domain/notice/comment/CommentRepository.java
  src/main/java/com/kgu/studywithme/study/domain/review/ReviewRepository.java
  src/main/java/com/kgu/studywithme/study/exception/CommentErrorCode.java
  src/main/java/com/kgu/studywithme/study/exception/NoticeErrorCode.java
  src/main/java/com/kgu/studywithme/study/service/StudyFindService.java
  src/main/java/com/kgu/studywithme/study/service/StudyReviewService.java
  src/main/java/com/kgu/studywithme/study/service/StudyValidator.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyReviewApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/review/ReviewRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyReviewServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyValidatorTest.java
Labels: feature

#111 [feat] 스터디별 공지사항 및 댓글 조회 API를 구현한다
  src/docs/asciidoc/study-information.adoc
  src/main/java/com/kgu/studywithme/global/annotation/ValidStudyParticipant.java
  src/main/java/com/kgu/studywithme/global/annotation/ValidStudyParticipantAspect.java
  src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
  src/main/java/com/kgu/studywithme/study/domain/StudyRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/CommentInformation.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/NoticeInformation.java
  src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/NoticeAssembler.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyHost.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyMember.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyReview.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/config/TestAopConfiguration.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
Labels: feature

#113 [refactor] 테스트 코드 추가 및 전체 코드 리팩토링을 진행한다
  src/docs/asciidoc/study-notice.adoc
  src/main/java/com/kgu/studywithme/auth/domain/TokenRepository.java
  src/main/java/com/kgu/studywithme/category/service/CategoryService.java
  src/main/java/com/kgu/studywithme/favorite/service/FavoriteManageService.java
  src/main/java/com/kgu/studywithme/member/controller/MemberApiController.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/java/com/kgu/studywithme/member/service/MemberService.java
  src/main/java/com/kgu/studywithme/member/utils/MemberAgeCalculator.java
  src/main/java/com/kgu/studywithme/study/controller/StudyParticipationApiController.java
  src/main/java/com/kgu/studywithme/study/controller/StudySearchApiController.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/NoticeRequest.java
  src/main/java/com/kgu/studywithme/study/controller/notice/StudyNoticeApiController.java
  src/main/java/com/kgu/studywithme/study/domain/notice/Notice.java
  src/main/java/com/kgu/studywithme/study/exception/CommentErrorCode.java
  src/main/java/com/kgu/studywithme/study/exception/NoticeErrorCode.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
  src/main/java/com/kgu/studywithme/study/service/notice/NoticeCommentService.java
  src/main/java/com/kgu/studywithme/study/service/notice/NoticeFindService.java
  src/main/java/com/kgu/studywithme/study/service/notice/NoticeService.java
  src/test/java/com/kgu/studywithme/auth/domain/TokenTest.java
  src/test/java/com/kgu/studywithme/auth/utils/AuthorizationExtractorTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberFindServiceTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberServiceTest.java
  src/test/java/com/kgu/studywithme/member/utils/MemberAgeCalculatorTest.java
  src/test/java/com/kgu/studywithme/study/controller/notice/StudyNoticeApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/notice/NoticeTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyFindServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/notice/NoticeFindServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/notice/NoticeServiceTest.java
Labels: refactor

#128 [feat] 사용자 피어리뷰 및 신고 도메인을 설계한다
  src/main/java/com/kgu/studywithme/member/domain/Email.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
  src/main/java/com/kgu/studywithme/member/domain/report/Report.java
  src/main/java/com/kgu/studywithme/member/domain/report/ReportRepository.java
  src/main/java/com/kgu/studywithme/member/domain/report/ReportStatus.java
  src/main/java/com/kgu/studywithme/member/domain/review/PeerReview.java
  src/main/java/com/kgu/studywithme/member/domain/review/PeerReviewRepository.java
  src/main/java/com/kgu/studywithme/member/domain/review/PeerReviews.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepository.java
  src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/domain/StudyName.java
  src/main/java/com/kgu/studywithme/study/domain/assignment/submit/Upload.java
  src/main/java/com/kgu/studywithme/study/domain/assignment/submit/UploadFile.java
  src/main/java/com/kgu/studywithme/study/domain/attendance/Attendance.java
  src/main/java/com/kgu/studywithme/study/domain/notice/comment/Comment.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/domain/report/ReportTest.java
  src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewTest.java
  src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewsTest.java
  src/test/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/submit/SubmitTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/submit/UploadFileTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/submit/UploadTest.java
  src/test/java/com/kgu/studywithme/study/domain/review/ReviewsTest.java
Labels: feature

#129 [feat] 스터디 신청자 조회에 대한 API를 구현한다
  src/docs/asciidoc/study-information.adoc
  src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/StudyApplicantInformation.java
  src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyApplicant.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
Labels: feature

#132 [feat] 사용자 신고를 위한 API를 구현한다
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member-report.adoc
  src/main/java/com/kgu/studywithme/member/controller/MemberApiController.java
  src/main/java/com/kgu/studywithme/member/controller/dto/request/MemberReportRequest.java
  src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
  src/main/java/com/kgu/studywithme/member/service/MemberService.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/controller/MemberApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/controller/utils/SignUpRequestUtils.java
  src/test/java/com/kgu/studywithme/member/service/MemberServiceTest.java
Labels: feature

#136 [feature] 사용자별 피어리뷰 조회 API를 구현한다
  src/docs/asciidoc/member-information.adoc
  src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
  src/main/java/com/kgu/studywithme/member/domain/review/PeerReviewRepository.java
  src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
  src/main/java/com/kgu/studywithme/member/service/dto/response/PeerReviewAssembler.java
  src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
  src/main/java/com/kgu/studywithme/study/controller/attendance/AttendanceApiController.java
  src/test/java/com/kgu/studywithme/common/ServiceTest.java
  src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
Labels: feature

#137 [feat & refactor] 스터디 도메인의 과제에 대한 개념을 주차별로 수정하고 주차별 첨부파일에 대한 도메인을 설계한다
  build.gradle
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/assignment/Assignment.java
  src/main/java/com/kgu/studywithme/study/domain/assignment/AssignmentRepository.java
  src/main/java/com/kgu/studywithme/study/domain/assignment/Assignments.java
  src/main/java/com/kgu/studywithme/study/domain/assignment/submit/UploadType.java
  src/main/java/com/kgu/studywithme/study/domain/attendance/AttendanceStatus.java
  src/main/java/com/kgu/studywithme/study/domain/week/Period.java
  src/main/java/com/kgu/studywithme/study/domain/week/Week.java
  src/main/java/com/kgu/studywithme/study/domain/week/WeekRepository.java
  src/main/java/com/kgu/studywithme/study/domain/week/Weekly.java
  src/main/java/com/kgu/studywithme/study/domain/week/attachment/Attachment.java
  src/main/java/com/kgu/studywithme/study/domain/week/attachment/AttachmentRepository.java
  src/main/java/com/kgu/studywithme/study/domain/week/submit/Submit.java
  src/main/java/com/kgu/studywithme/study/domain/week/submit/SubmitRepository.java
  src/main/java/com/kgu/studywithme/study/domain/week/submit/Upload.java
  src/main/java/com/kgu/studywithme/study/domain/week/submit/UploadType.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/test/java/com/kgu/studywithme/fixture/AttachmentFixture.java
  src/test/java/com/kgu/studywithme/fixture/PeriodFixture.java
  src/test/java/com/kgu/studywithme/fixture/WeekFixture.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentTest.java
  src/test/java/com/kgu/studywithme/study/domain/assignment/AssignmentsTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceStatusTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/PeriodTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/WeekTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/WeeklyTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/attachment/AttachmentTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/submit/SubmitTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/submit/UploadTest.java
Labels: feature, refactor

#138 [feat] 스터디 출석 현황 조회 API를 구현한다
  src/docs/asciidoc/study-information.adoc
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/attendance/Attendance.java
  src/main/java/com/kgu/studywithme/study/domain/week/Week.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/AttendanceInformation.java
  src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/AttendanceAssmbler.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/AttendanceSummary.java
  src/test/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberReviewServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/attendance/AttendanceServiceTest.java
Labels: feature

#140 [feat] 파일 저장을 위한 NCP Object Storage 관련 설정을 진행한다
  build.gradle
  src/docs/asciidoc/image-upload.adoc
  src/main/java/com/kgu/studywithme/global/annotation/ValidImageExtension.java
  src/main/java/com/kgu/studywithme/global/annotation/ValidImageExtensionValidator.java
  src/main/java/com/kgu/studywithme/global/config/AmazonS3Configuration.java
  src/main/java/com/kgu/studywithme/upload/controller/ImageUploadApiController.java
  src/main/java/com/kgu/studywithme/upload/controller/dto/request/ImageUploadRequest.java
  src/main/java/com/kgu/studywithme/upload/exception/UploadErrorCode.java
  src/main/java/com/kgu/studywithme/upload/utils/AmazonS3Properties.java
  src/main/java/com/kgu/studywithme/upload/utils/BucketMetadata.java
  src/main/java/com/kgu/studywithme/upload/utils/FileUploader.java
  src/main/resources/application-test.yml
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/common/utils/FileMockingUtils.java
  src/test/java/com/kgu/studywithme/global/annotation/ValidImageExtensionValidatorTest.java
  src/test/java/com/kgu/studywithme/upload/controller/ImageUploadApiControllerTest.java
  src/test/java/com/kgu/studywithme/upload/utils/AmazonS3PropertiesTest.java
  src/test/java/com/kgu/studywithme/upload/utils/FileUploaderTest.java
  src/test/resources/files/hello1.txt
  src/test/resources/files/hello2.hwpx
  src/test/resources/files/hello3.pdf
  src/test/resources/files/hello4.png
  src/test/resources/files/hello5.webp
Labels: feature

#144 [feat] 스터디 주차 등록 및 주차별 과제 제출 API를 구현한다
  src/docs/asciidoc/study-weekly.adoc
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyWeeklyRequest.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/WeeklyAssignmentSubmitRequest.java
  src/main/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiController.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/attendance/AttendanceRepository.java
  src/main/java/com/kgu/studywithme/study/domain/week/Period.java
  src/main/java/com/kgu/studywithme/study/domain/week/Week.java
  src/main/java/com/kgu/studywithme/study/domain/week/WeekRepository.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/service/week/StudyWeeklyService.java
  src/main/java/com/kgu/studywithme/upload/controller/ImageUploadApiController.java
  src/test/java/com/kgu/studywithme/category/service/CategoryServiceTest.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/fixture/WeekFixture.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/utils/StudyWeeklyRequestUtils.java
  src/test/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/PeriodTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/WeekRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/WeekTest.java
  src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyReviewServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
Labels: feature

#146 [feat] 스터디 각 주차별 정보 조회 API를 구현한다
  src/docs/asciidoc/study-information.adoc
  src/main/java/com/kgu/studywithme/member/utils/MemberAgeCalculator.java
  src/main/java/com/kgu/studywithme/study/controller/StudyInformationApiController.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/participant/Participants.java
  src/main/java/com/kgu/studywithme/study/domain/week/submit/UploadType.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/service/StudyInformationService.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/WeeklyAssembler.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/WeeklySubmitSummary.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/WeeklySummary.java
  src/test/java/com/kgu/studywithme/fixture/MemberFixture.java
  src/test/java/com/kgu/studywithme/member/utils/MemberAgeCalculatorTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/participant/ParticipantsTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
Labels: feature

#148 [fix] 스터디 각 주차별 조회시 첨부파일이나 과제 제출자가 없을 경우 조회가 안되는 문제를 해결한다
  src/docs/asciidoc/image-upload.adoc
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/upload/controller/UploadApiController.java
  src/test/java/com/kgu/studywithme/common/ControllerTest.java
  src/test/java/com/kgu/studywithme/fixture/AttachmentFixture.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
  src/test/java/com/kgu/studywithme/upload/controller/UploadApiControllerTest.java
Labels: bug

#149 [feat] 서버 API 예외에 대한 Slack API 알림 기능을 구현한다
  build.gradle
  src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
  src/main/java/com/kgu/studywithme/global/slack/SlackMetadata.java
  src/main/resources/application-test.yml
Labels: feature

#151 [feat] 스터디 참여 승인/거부 및 졸업 시 해당 사용자에게 메일을 발송한다
  build.gradle
  src/docs/asciidoc/study-participation.adoc
  src/main/java/com/kgu/studywithme/global/config/AsyncConfiguration.java
  src/main/java/com/kgu/studywithme/global/exception/ApiGlobalExceptionHandler.java
  src/main/java/com/kgu/studywithme/global/mail/event/StudyParticipationEventListener.java
  src/main/java/com/kgu/studywithme/global/mail/utils/EmailMetadata.java
  src/main/java/com/kgu/studywithme/global/mail/utils/EmailSender.java
  src/main/java/com/kgu/studywithme/study/controller/StudyParticipationApiController.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/ParticipationRejectRequest.java
  src/main/java/com/kgu/studywithme/study/event/StudyApprovedEvent.java
  src/main/java/com/kgu/studywithme/study/event/StudyGraduatedEvent.java
  src/main/java/com/kgu/studywithme/study/event/StudyRejectedEvent.java
  src/main/java/com/kgu/studywithme/study/service/ParticipationService.java
  src/main/resources/application-test.yml
  src/main/resources/templates/ParticipationApproveEmailTemplate.html
  src/main/resources/templates/ParticipationRejectEmailTemplate.html
  src/main/resources/templates/StudyCertificateEmailTemplate.html
  src/test/java/com/kgu/studywithme/study/controller/StudyParticipationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/service/ParticipationServiceTest.java
Labels: feature

#155 [feat] 사용자 출석률 조회에 대한 API를 구현한다
  src/docs/asciidoc/member-information.adoc
  src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
  src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepository.java
  src/main/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/member/infra/query/dto/response/AttendanceRatio.java
  src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
  src/main/java/com/kgu/studywithme/member/service/dto/response/AttendanceRatioAssembler.java
  src/main/java/com/kgu/studywithme/member/service/dto/response/MemberInformation.java
  src/main/java/com/kgu/studywithme/study/domain/attendance/AttendanceStatus.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
  src/test/java/com/kgu/studywithme/global/annotation/validation/ValidHashtagCountValidatorTest.java
  src/test/java/com/kgu/studywithme/global/annotation/validation/ValidImageExtensionValidatorTest.java
  src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/infra/query/MemberSimpleQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceStatusTest.java
Labels: feature

#157 [refactor] 메인페이지 스터디 조회 쿼리 최적화를 진행한다
  src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicStudy.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/NoticeInformation.java
  src/main/java/com/kgu/studywithme/study/service/StudySearchService.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
Labels: refactor

#159 [refactor] 스터디 썸네일 이미지를 추가한다
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyRegisterRequest.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/com/kgu/studywithme/study/domain/Study.java
  src/main/java/com/kgu/studywithme/study/domain/StudyThumbnail.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicStudy.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/SimpleStudy.java
  src/main/java/com/kgu/studywithme/study/service/StudyService.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
  src/test/java/com/kgu/studywithme/fixture/StudyFixture.java
  src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/utils/StudyRegisterRequestUtils.java
  src/test/java/com/kgu/studywithme/study/controller/utils/StudyUpdateRequestUtils.java
  src/test/java/com/kgu/studywithme/study/domain/StudyTest.java
  src/test/java/com/kgu/studywithme/study/domain/StudyThumbnailTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyServiceTest.java
Labels: refactor

#162 [refactor] 스터디 각 썸네일에 대한 고유 색상 필드를 추가한다
  src/main/java/com/kgu/studywithme/study/domain/StudyThumbnail.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicStudy.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/SimpleStudy.java
  src/main/java/com/kgu/studywithme/study/service/dto/response/StudyInformation.java
  src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudySearchApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
Labels: refactor

#163 [feat] 마이페이지에서 신청 대기 상태인 스터디 리스트를 조회하기 위한 API를 구현한다
  src/docs/asciidoc/member-information.adoc
  src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
  src/main/java/com/kgu/studywithme/member/service/MemberInformationService.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
  src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/service/MemberInformationServiceTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
Labels: feature

#165 [feat] 스터디 종료 API를 구현한다
  src/docs/asciidoc/study-update.adoc
  src/main/java/com/kgu/studywithme/study/controller/StudyApiController.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyCategoryQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/service/StudyService.java
  src/test/java/com/kgu/studywithme/study/controller/StudyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/service/StudySearchServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyServiceTest.java
Labels: feature

#167 [feat] 사용자 점수 메커니즘 및 자동 결석 처리에 대한 스케줄링 로직을 구현한다
  src/docs/asciidoc/study-attendance.adoc
  src/main/java/com/kgu/studywithme/auth/domain/TokenRepository.java
  src/main/java/com/kgu/studywithme/global/config/AsyncConfiguration.java
  src/main/java/com/kgu/studywithme/global/config/SchedulingConfiguration.java
  src/main/java/com/kgu/studywithme/global/config/TimeZoneConfiguration.java
  src/main/java/com/kgu/studywithme/global/mail/event/StudyParticipationEventListener.java
  src/main/java/com/kgu/studywithme/member/domain/Member.java
  src/main/java/com/kgu/studywithme/member/domain/Score.java
  src/main/java/com/kgu/studywithme/study/controller/attendance/AttendanceApiController.java
  src/main/java/com/kgu/studywithme/study/domain/attendance/Attendance.java
  src/main/java/com/kgu/studywithme/study/domain/attendance/AttendanceRepository.java
  src/main/java/com/kgu/studywithme/study/domain/notice/comment/CommentRepository.java
  src/main/java/com/kgu/studywithme/study/domain/participant/ParticipantRepository.java
  src/main/java/com/kgu/studywithme/study/domain/week/WeekRepository.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepository.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicAttendance.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/BasicWeekly.java
  src/main/java/com/kgu/studywithme/study/service/attendance/AttendanceService.java
  src/main/java/com/kgu/studywithme/study/service/scheduler/StudyAttendanceScheduler.java
  src/main/java/com/kgu/studywithme/study/service/week/StudyWeeklyService.java
  src/main/resources/application-test.yml
  src/test/java/com/kgu/studywithme/fixture/StudyFixture.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/domain/ScoreTest.java
  src/test/java/com/kgu/studywithme/study/controller/attendance/AttendanceApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/attendance/AttendanceTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/WeekRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudySimpleQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/attendance/AttendanceServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
Labels: feature

#169 [feat] 제출한 과제에 대한 수정 API를 구현한다
  src/docs/asciidoc/study-weekly.adoc
  src/main/java/com/kgu/studywithme/global/annotation/validation/ValidUploadType.java
  src/main/java/com/kgu/studywithme/global/annotation/validation/ValidUploadTypeValidator.java
  src/main/java/com/kgu/studywithme/study/controller/dto/request/WeeklyAssignmentSubmitRequest.java
  src/main/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiController.java
  src/main/java/com/kgu/studywithme/study/domain/week/submit/Submit.java
  src/main/java/com/kgu/studywithme/study/domain/week/submit/SubmitRepository.java
  src/main/java/com/kgu/studywithme/study/exception/StudyErrorCode.java
  src/main/java/com/kgu/studywithme/study/service/week/StudyWeeklyService.java
  src/test/java/com/kgu/studywithme/global/annotation/validation/ValidStudyTypeValidatorTest.java
  src/test/java/com/kgu/studywithme/global/annotation/validation/ValidUploadTypeValidatorTest.java
  src/test/java/com/kgu/studywithme/study/controller/week/StudyWeeklyApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/submit/SubmitRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/submit/SubmitTest.java
  src/test/java/com/kgu/studywithme/study/domain/week/submit/UploadTest.java
  src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
  src/test/java/com/kgu/studywithme/upload/utils/FileUploaderTest.java
Labels: feature

#172 [fix] 결석 처리에 대한 스케줄링 시 결석자에 대한 Score 업데이트 누락을 추가한다
  src/main/java/com/kgu/studywithme/member/domain/MemberRepository.java
  src/main/java/com/kgu/studywithme/member/domain/Score.java
  src/main/java/com/kgu/studywithme/member/service/dto/response/MemberInformation.java
  src/main/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryImpl.java
  src/main/java/com/kgu/studywithme/study/infra/query/dto/response/StudyApplicantInformation.java
  src/main/java/com/kgu/studywithme/study/service/scheduler/StudyAttendanceScheduler.java
  src/test/java/com/kgu/studywithme/member/controller/MemberInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/domain/ScoreTest.java
  src/test/java/com/kgu/studywithme/study/controller/StudyInformationApiControllerTest.java
  src/test/java/com/kgu/studywithme/study/infra/query/StudyInformationQueryRepositoryTest.java
  src/test/java/com/kgu/studywithme/study/service/StudyInformationServiceTest.java
Labels: bug

#174 [refactor] 사용자 점수 메커니즘을 수정한다
  src/main/java/com/kgu/studywithme/member/domain/Score.java
  src/test/java/com/kgu/studywithme/member/domain/MemberRepositoryTest.java
  src/test/java/com/kgu/studywithme/member/domain/MemberTest.java
  src/test/java/com/kgu/studywithme/member/domain/ScoreTest.java
  src/test/java/com/kgu/studywithme/study/service/attendance/AttendanceServiceTest.java
  src/test/java/com/kgu/studywithme/study/service/week/StudyWeeklyServiceTest.java
Labels: refactor
